steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-custom:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-custom:latest']

  # Step 3: SSH into the instance through IAP and run the deployment script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh instance-testing \
          --project=$PROJECT_ID \
          --tunnel-through-iap \
          --zone=us-central1-c \
          --command="bash deploy.sh"

images:
  - 'gcr.io/$PROJECT_ID/nginx-custom:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only


