steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-custom:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-custom:latest']

  # Step 3: Deploy the container to the Compute Engine instance using `update-container`
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'instance-20241108-103346'  # Using instance name 'yokai'
      - '--zone=us-central1-a'
      - '--container-image=gcr.io/$PROJECT_ID/nginx-custom:latest'
      - '--container-restart-policy=always'  # Optional: configure as needed    # Optional: pass arguments to container
       # Optional: set environment variables

images:
  - 'gcr.io/$PROJECT_ID/nginx-custom:latest'

options:
  logging: CLOUD_LOGGING_ONLY
