steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-custom:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-custom:latest']


  # Step 4: SSH into the instance and run the deployment script
 steps:
  # Step 1: SSH into the instance through IAP and run a command
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh INSTANCE_NAME \
          --project=$PROJECT_ID \
          --zone=ZONE \
          --tunnel-through-iap \
          --command="bash deploy.sh"
images:
  - 'gcr.io/$PROJECT_ID/nginx-custom:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Change logging to use cloud logging only

