steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-custom:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-custom:latest']

  # Step 3: SSH into the instance and run the deployment script
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-testing'  # Your instance name
      - '--zone'
      - 'us-central1-a'  # Replace with your zone
      - '--command'
      - 'bash ~/deploy.sh'  # Update this path if necessary based on where the script is located

images:
  - 'gcr.io/$PROJECT_ID/nginx-custom:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Change logging to use cloud logging only
